### PR TITLE
Micro-Reddit

### PR DESCRIPTION
**Pull request by angelacuahutle**
Dear TSE, 
We have created a Micro-Reddit in order to implement our knowledge in active record with RoR. We implemented linters and a simple Readme file.

### CODE REVIEW

**Review by BrianSammit — COMMENTED** [review]
STATUS INVALID :yellow_circle: 
-------
Hello @angelacuahutle @enionsouza  :wave: 

Friendly reminder: You should make sure that your repo looks professional before review. you don't have a descriptive README.md. Please add the readme file, [Here](https://github.com/microverseinc/readme-template) you can find a template for the readme file. 
Also, check the Git Flow, remember that the development branch must be the default branch. [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/) you can have a refresh about the Git Flow. 
Please make those requirements and send it again for another review.

**Comment by angelacuahutle** [comment]
Dear TSE, 
We have made the changes according to what was requested. 
[x] Implemented Readme with the correct format 
[x] Change the default branch to development

Thanks

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
----------
Hello there again :wave: Great job working on this project. :+1: :100: 

TO HIGHLIGHT: 

- Your project is professional.
- Your repo is professional.
- Well use of the validations. 
- Great job implementing more validation and not only the present. 
- Great job working with the associations

However, you need to make a minor change. :hammer_and_wrench: see it below :point_down: 

---------------
- [x] On your readme file, on the 'INSTALL' section please change the command `rails server` to `rails console` because you did not make any view. Also, remove the next line `IN your browser you should go to http://127.0.0.1:3000/`
- [x] [OPTIONAL] Remove the `Live Demo` section because you don't have any live demo.
- [ ] [OPTIONAL] You can write the commands that they need to run in the console to create a user, post, and comment. 
- [x] [OPTIONAL] Please remove the image from your readme you don't need to show this because in this project you did not work with views. Instead, you can make a screenshot to your console showing how to create a user, post, and comment. 
-----------------
Make this minor change and send it again for another review :1st_place_medal: :muscle: 
Reachme on SALCK if you have any questions: 
@ Brian Sammit Cruz Rodriguez
HAPPY CODING!!!

MB5W4D

**Review by george-shammar — APPROVED** [review]
STATUS:APPROVED :heavy_check_mark: :heavy_check_mark: 

Well done and thank you for implementing the required changes from the previous review. :+1: :clap: 

Your repo looks professional too. :clap: 

Please go ahead and merge this branch.

**I wish you good luck with your future project.**

**Cheers** :smile:

**Pull request merged**
